"""schema inicial

Revision ID: 350a2ac61a43
Revises: 
Create Date: 2026-07-30 18:19:17.582788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '350a2ac61a43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('painel_solar', 'inversor', 'outro', name='produtotipo', native_enum=False, length=20), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('modelo', sa.String(length=150), nullable=True),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'desativado', name='produtostatus', native_enum=False, length=20), nullable=False),
    sa.Column('specs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.String()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('ddd', sa.String(length=3), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('cnpj_cpf', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('municipio_cod_ibge', sa.String(length=10), nullable=False),
    sa.Column('municipio_nome', sa.String(length=120), nullable=False),
    sa.Column('estado_uf', sa.String(length=2), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('tipo_residencia', sa.Enum('Residencial', 'Comercial', 'Industrial', 'Rural', name='tiporesidencia', native_enum=False, length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_proposta', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('tipo_orcamento', sa.Enum('sistema_completo', 'itens_individuais', name='tipoorcamento', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('rascunho', 'enviado', 'aguardando_resposta', 'confirmado', 'cancelado', name='orcamentostatus', native_enum=False, length=30), nullable=False),
    sa.Column('margem_lucro_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('validade_dias', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_numero_proposta'), 'budgets', ['numero_proposta'], unique=True)
    op.create_table('budget_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('tipo_item', sa.Enum('painel', 'inversor', 'parte_ca', 'mao_obra', 'homologacao', 'outro', name='tipoitem', native_enum=False, length=20), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('custo_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_solar_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('consumo_mensal_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_conta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_telhado', sa.Enum('ceramico', 'fibrocimento', 'metalico', 'laje', 'solo', name='tipotelhado', native_enum=False, length=30), nullable=False),
    sa.Column('orientacao', sa.Enum('norte', 'nordeste', 'noroeste', 'leste_oeste', name='orientacao', native_enum=False, length=20), nullable=False),
    sa.Column('distribuidora', sa.String(length=60), nullable=False),
    sa.Column('area_disponivel_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('painel_product_id', sa.Integer(), nullable=False),
    sa.Column('potencia_wp_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('qtd_paineis_override', sa.Integer(), nullable=True),
    sa.Column('inversor_product_id', sa.Integer(), nullable=False),
    sa.Column('qtd_inversores_override', sa.Integer(), nullable=True),
    sa.Column('potencia_wp_utilizada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_kw_inversor_utilizada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('radiacao_media_regiao', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('radiacao_ajustada', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('qtd_paineis_sugerido', sa.Integer(), nullable=False),
    sa.Column('qtd_paineis', sa.Integer(), nullable=False),
    sa.Column('potencia_sistema_kwp', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('qtd_inversores_sugerido', sa.Integer(), nullable=False),
    sa.Column('qtd_inversores', sa.Integer(), nullable=False),
    sa.Column('geracao_estimada_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('municipio_fallback_usado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['inversor_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['painel_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id')
    )
    op.create_table('budget_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('status_anterior', sa.Enum('rascunho', 'enviado', 'aguardando_resposta', 'confirmado', 'cancelado', name='orcamentostatus', native_enum=False, length=30), nullable=True),
    sa.Column('status_novo', sa.Enum('rascunho', 'enviado', 'aguardando_resposta', 'confirmado', 'cancelado', name='orcamentostatus', native_enum=False, length=30), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_status_history')
    op.drop_table('budget_solar_config')
    op.drop_table('budget_items')
    op.drop_index(op.f('ix_budgets_numero_proposta'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
