"""lead status

Revision ID: b5900ed0b5aa
Revises: dcd27d5ca032
Create Date: 2026-08-24 20:31:05.524129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5900ed0b5aa'
down_revision: Union[str, Sequence[str], None] = 'dcd27d5ca032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'public_leads',
        sa.Column(
            'status',
            sa.Enum('novo', 'em_contato', 'orcamento_enviado', 'convertido', 'descartado', name='leadstatus', native_enum=False, length=20),
            nullable=False,
            server_default='novo',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_leads', 'status')
    # ### end Alembic commands ###
