"""public leads

Revision ID: dcd27d5ca032
Revises: 7a1f2c9e4d3b
Create Date: 2026-08-24 19:45:43.461007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd27d5ca032'
down_revision: Union[str, Sequence[str], None] = '7a1f2c9e4d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('interesse', sa.Enum('energia_solar', 'mobilidade_eletrica', 'ambos', name='interesselead', native_enum=False, length=30), nullable=False),
    sa.Column('consumo_medio_mensal', sa.Enum('ate_200', 'de_201_a_500', 'de_501_a_700', 'de_701_a_1000', 'acima_de_1000', name='consumomediomensal', native_enum=False, length=30), nullable=True),
    sa.Column('tipo_projeto', sa.Enum('Residencial', 'Comercial', 'Industrial', 'Rural', name='tiporesidencia', native_enum=False, length=20), nullable=True),
    sa.Column('quando_pretende_investir', sa.Enum('agora', 'proximos_3_meses', 'proximos_6_meses_a_1_ano', 'ainda_pesquisando', name='quandopretendeinvestir', native_enum=False, length=40), nullable=True),
    sa.Column('faixa_parcela_mensal', sa.Enum('ate_300', 'de_301_a_500', 'em_torno_de_699', 'acima_de_700', name='faixaparcelamensal', native_enum=False, length=30), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_leads')
    # ### end Alembic commands ###
